### ISSUE TITLE
Update to libsrtp 2.3.0

### ISSUE THREAD

**Issue by nashley** [HyeonuPark/srtp2-sys#1]
The latest version as of writing is [`2.3.0`](https://github.com/cisco/libsrtp/releases/tag/v2.3.0), but these bindings are for `2.2.0`. [The differences](https://github.com/cisco/libsrtp/blob/v2.3.0/CHANGES) aren't huge, but it'd be nice to bring this repo up-to-date.

**Comment by HyeonuPark** [comment]
Thanks for letting me know that! I'll publish new version of srtp2-sys and srtp soon.

**Comment by nashley** [comment]
Awesome; thank you for maintaining this and for being so prompt!

**Comment by HyeonuPark** [comment]
Updated to use libsrtp v2.3.0
